[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[projekt]
name = "synthetic-politics"
version ="0.0.1"
description = " generation of synthetic parliament speeches"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]